create table
  public.asian_categories (
    id bigint generated by default as identity,
    name character varying null,
    element_id character varying null,
    constraint asian_categories_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.asian_elements (
    id uuid not null default gen_random_uuid (),
    name character varying null,
    summary text null,
    url character varying null,
    constraint asian_elements_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.asian_item_images (
    id bigint generated by default as identity,
    item_id character varying null,
    image text null,
    constraint asian_item_images_pkey primary key (id)
  ) tablespace pg_default;


  create table
  public.asian_items (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    sites_url character varying null,
    name character varying null,
    email character varying null,
    phone_number character varying null,
    address character varying null,
    details character varying null,
    reviews character varying null,
    geo_lati real null,
    geo_lon real null,
    category_id character varying null,
    image text null,
    page_type_id character varying null,
    element_id character varying null,
    constraint asian_items_pkey primary key (id)
  ) tablespace pg_default;
  